export const HOME_SCREEN = "HOME_SCREEN";
export const LOGIN_SCREEN = "LOGIN_SCREEN";
export const REGISTER_SCREEN = "REGISTER_SCREEN";
export const GETTING_STARTED_SCREEN = "GETTING_STARTED_SCREEN";
export const PLACE_SCREEN = "PLACE_SCREEN";
